"""Schema update

Revision ID: 073b25b8c31d
Revises: 8b0cca115f75
Create Date: 2024-10-20 21:08:14.017037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073b25b8c31d'
down_revision: Union[str, None] = '8b0cca115f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('datetime', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'datetime')
    # ### end Alembic commands ###
